/*
QUESTION 1: HOW DO WE MOVE THE TWIG ONLY WHEN THE CROC IS CONFIRMED TO MOVE TOWARD IT?
QUESTION 2: HOW DO WE MAKE THE TWIG MOVE IN A TILE FORMAT?

IDEA 1: TWIG SHOULD SENSE IF A CROC EXISTS IN 1 PIXEL'S DISTANCE FROM ITSELF
		IF THERE IS A CROC
		AND THE CROC IS MOVING AT X SPEED
		AND THE CROC'S DIRECTION IS MOVING IT TOWARD THE TWIG
			THEN DO WORK
			
NOTE: IF A TWIG IS GOING TO MOVE INTO ANOTHER TILE,
	1. THAT TILE MUST BE EMPTY
	2. THAT TILE MUST THEN BE CLAIMED
	3. ONLY WHEN MOVEMENT IS COMPLETE, WE CLEAR ORIGINAL TILE
*/
function LunaInitialize()
{

}